config/routes.rb
Rails.application.routes.draw do

  root "questions#index"
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  resources :users
  resources :questions do
    resources :votes, only: [:create]
    resources :comments, only: [:new, :create, :destroy]
    resources :answers, only: [:new, :create, :destroy, :show] do
      resources :comments, only: [:new, :create, :destroy]
      resources :votes, only: [:create]
    end
  end
  resources :tags
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessor :new_tags
  belongs_to :user
  has_many :comments, as: :response, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :question_tags, dependent: :destroy
  has_many :tags, through: :question_tags
  has_many :votes, as: :tally, dependent: :destroy

  validates :title, presence: true
  validates :content, presence: true
  validates :user, presence: true
  validate :title_must_not_be_nil
  validate :content_must_not_be_nil

  def vote_count
    self.votes.inject(0) {|x, y| x + y.value}
  end

  def answer_count
    self.answers.count
  end

  def content_must_not_be_nil
    if self.content.length == 0
      errors.add(:content, "You entered a blank description.")
    end
  end

  def title_must_not_be_nil
    if self.title.length == 0
      errors.add(:title, "You entered a blank title")
    end
  end

  def new_tags=(tags_from_form)
    self.new_tags = tags_from_form.gsub(",", "").split(' ')
  end

  def time_since_creation
    ((Time.now - created_at) / 3600).round
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @questions = Question.all
  end

  def new
    if logged_in?
      @question = Question.new
    else
      redirect_to root_path
    end
  end

  def create
    @question = current_user.questions.new(question_params)

    if @question.save
      tag_finder
      redirect_to questions_path
    else
      @errors = @question.errors.full_messages.join(', ')
      render :new
    end
  end

  def show
    @question = Question.find_by(id: params[:id])
  end

  def destroy
  end

  def update
  end

  def edit
  end

  private

  def tag_finder
    @tags = tag_params.to_a.flatten
    unless @tags.empty?
      @tags[1].gsub(/\W+/, ' ').split(' ').each do |tag|
        @tag = Tag.find_by(title: tag)
        if @tag
          @tag.question_tags.create(question: @question)
        else
          @new_tag = Tag.create(title: tag).question_tags.create(question: @question)
        end
      end
    end
  end

  def question_params
    params.require(:question).permit(:title, :content)
  end

  def tag_params
    params.require(:question).permit(:new_tags)
  end
end

app/views/questions/_question.html.erb
<h3>Question</h3>
<div class="question-container">
  <div class="vote-container">
    <%= button_to '+', question_votes_path(@question.id), params: {vote_value: 1}, remote: true, authenticity_token: true  %>
    <span id='vote-counter'><%= @question.vote_count %><br></span>
    <%= button_to '-', question_votes_path(@question.id), params: {vote_value: -1}, remote: true, authenticity_token: true  %>
  </div>
  <div class="q-title-content">
    <%=@question.title%><br>
    <%=@question.content%>
  </div>
</div>

app/views/questions/index.html.erb
<div id='questions'>

<table class="q-display-table">
    <% @questions.each do |question| %>
  <tr>
    <td class="votes"><%=question.vote_count %><br>votes</td>
    <td class="answers"><%=question.answer_count %><br>answers</td>
    <td class="question-tag"><%=link_to "#{question.title}", question_path(question.id) %><br>
      <%question.tags.each do |tag|%>
      <%=link_to "#{tag.title}", tag_path(tag.id), {class: "tags"}%>
      <%end%></td>
      <td class="user-time"><%=question.user.username %><br><%="#{question.time_since_creation} hours ago"%></td>
  </tr>
    <% end %>
</table>


</div>

app/views/questions/new.html.erb
<div class="new-question-page">
  <h1>Create a New Question</h1>

  <div class="errors-partial">
    <% render "/shared/errors" %>
  </div>

  <div class="new-question-form">
    <%= form_for :question, url: questions_path do |f| %>
      <p>
        <%= f.label :title %><br>
        <%= f.text_field :title %>
      </p>

      <p>
        <%= f.label :content %><br>
        <%= f.text_area :content %>
      </p>

      <p>
        <%= f.label :new_tags %><br>
        <%= f.text_field :new_tags %>
      </p>

      <p>
        <%= f.submit "Submit Your Question" %>
      </p>
    <% end %>
  </div>
</div>

app/views/questions/show.html.erb
<div class="question-page">

	<div class="render-question">
    <%=render 'questions/question' %>
  </div>
  <div class="q-comment">
    <% @question.comments.each do |comment| %>
    <% @old_comment = comment %>
    <div class="render-q-comment">
      <%=render 'comments/show' %>
    </div>
    <%end%>
  </div>
  <div class="new-q-comment">
    <%=render 'comments/new_q_comment'%>
  </div>
  <div class="all-answer">
    <% @question.answers.each do |answer|%>
    <% @old_answer = answer%>
    <div class="render-answer">
      <%=render 'answers/show'%>
    </div>
    <div class="a-comment">
      <% answer.comments.each do |comment|%>
      <% @old_comment = comment %>
      <div class="render-a-comment">
        <%=render 'comments/show'%>
      </div>
      <%end%>
    </div>
    <div class="new-a-comment">
      <%=render 'comments/new_a_comment'%>
    </div>
    <%end%>
  </div>
  <div class="new-answer">
    <%=render 'answers/new'%>
  </div>

</div>