config/routes.rb
Rails.application.routes.draw do

  root "questions#index"
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  resources :users
  resources :questions do
    resources :votes, only: [:create]
    resources :comments, only: [:new, :create, :destroy]
    resources :answers, only: [:new, :create, :destroy, :show] do
      resources :comments, only: [:new, :create, :destroy]
      resources :votes, only: [:create]
    end
  end
  resources :tags
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :response, polymorphic: true

  validates :content, presence: true
  validates :user, presence: true
  validates :response, presence: true
  validate :content_must_not_be_nil

  def content_must_not_be_nil
    if self.content.length == 0
      errors.add(:content, "You entered a blank comment")
    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @comment = Comment.new
  end

  def create
    @comment = parent.comments.new(comment_params)
    @comment.update_attributes(user: current_user)

    if @comment.save
      respond_to do |format|
        format.js do
          if parent_string == "answer"
            render partial: 'add_new_ajax_to_a' and return
          else
            render partial: 'add_new_ajax_to_q' and return
          end
        end
        format.any do
          redirect_to question_path(params[:question_id])
        end
      end
    else
      @errors = @comment.errors.full_messages.join(', ')
      render :nothing => true
    end
  end

  private

  def parent
    answer = Answer.find_by(id: params[:answer_id])
    return answer if answer
    Question.find_by(id: params[:question_id])
  end

  def parent_string
    answer = Answer.find_by(id: params[:answer_id])
    return "answer" if answer
    "question"
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/views/comments/_add_new_ajax_to_a.html.erb
<div class="render-a-comment">
  <%= @comment.content %>
</div>

app/views/comments/_add_new_ajax_to_q.html.erb
<div class="render-q-comment">
  <%= @comment.content %>
</div>

app/views/comments/_new.html.erb
<div class="add-new-comment">
  <h3>Add a New Comment</h3>

  <div class="errors-partial">
    <% render "/shared/errors" %>
  </div>

  <div class="new-comment-form">
    <%= form_for :comment, url: question_answers_path(@question.id), method: :create do |f| %>

      <p>
        <%= f.label :content %><br>
        <%= f.text_area :content %>
      </p>

      <p>
        <%= f.submit "Submit Your Answer" %>
      </p>
    <% end %>
  </div>
</div>

app/views/comments/_new_a_comment.html.erb
<div class="add-new-comment">
  <h3>Add a New Comment</h3>

  <div class="errors-partial">
    <% render "/shared/errors" %>
  </div>

  <div class="new-a-comment-form">
     <%= form_for :comment, url: question_answer_comments_path(@question.id, @old_answer.id), remote: true, authenticity_token: true, method: :create do |f| %>

      <p>
        <%= f.text_area :content %>
      </p>

      <p>
        <%= f.submit "Leave Your Comment" %>
      </p>
    <% end %>
  </div>
</div>

app/views/comments/_new_q_comment.html.erb
<div class="add-new-comment">
  <h3>Add a New Comment</h3>

  <div class="errors-partial">
    <% render "/shared/errors" %>
  </div>

  <div class="new-q-comment-form">
     <%= form_for :comment, url: question_comments_path(@question.id), remote: true, authenticity_token: true, method: :create do |f| %>

      <p>
        <%= f.text_area :content %>
      </p>

      <p>
        <%= f.submit "Leave Your Comment" %>
      </p>
    <% end %>
  </div>
</div>

app/views/comments/_show.html.erb
<%= @old_comment.content %>