config/routes.rb
Rails.application.routes.draw do

  root "questions#index"
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  resources :users
  resources :questions do
    resources :votes, only: [:create]
    resources :comments, only: [:new, :create, :destroy]
    resources :answers, only: [:new, :create, :destroy, :show] do
      resources :comments, only: [:new, :create, :destroy]
      resources :votes, only: [:create]
    end
  end
  resources :tags
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :question
  has_many :comments, as: :response, dependent: :destroy
  has_many :votes, as: :tally, dependent: :destroy

  validates :content, presence: true
  validates :user, presence: true
  validates :question, presence: true
  validate :content_must_not_be_nil


  def vote_count
    self.votes.inject(0) {|x, y| x + y.value}
  end

  def content_must_not_be_nil
    if self.content.length == 0
      errors.add(:content, "You entered a blank answer")
    end
  end

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def new
    @answer = Answer.new
  end

  def create
    @question = Question.find_by(id: params[:question_id])
    @answer = @question.answers.new(answer_params)
    @answer.update_attributes(user: current_user)
    if @answer.save
      respond_to do |format|
        format.js do
          render partial: 'add_ajax_answer' and return
        end
        format.any do
          redirect_to question_path(params[:question_id])
        end
      end
    else
      @errors = @answer.errors.full_messages.join(', ')
      render :nothing => true
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:content)
  end
end

app/views/answers/_add_ajax_answer.html.erb
<div class="answer-container">
  <h3>Answer</h3>
    <div class="vote-container">
      <%= button_to '+', question_answer_votes_path(@question.id, @answer.id), params: {vote_value: 1}, remote: true, authenticity_token: true  %>
      <span id='vote-counter'><%= 0 %><br></span>
      <%= button_to '-', question_answer_votes_path(@question.id, @answer.id), params: {vote_value: -1}, remote: true, authenticity_token: true   %>
      <%= @answer.content %><br>
    </div>
    <div class="add-new-comment">
      <h3>Add a New Comment</h3>
      <div class="errors-partial">
        <% render "/shared/errors" %>
      </div>
      <div class="new-a-comment-form">
       <%= form_for :comment, url: question_answer_comments_path(@question.id, @answer.id), remote: true, authenticity_token: true, method: :create do |f| %>

        <p>
          <%= f.text_area :content %>
        </p>

        <p>
          <%= f.submit "Leave Your Comment" %>
        </p>
      <% end %>
      </div>
    </div>
</div>

app/views/answers/_new.html.erb
<div class="add-new-answer">
  <h3>Answer this Question</h3>

  <div class="errors-partial">
    <% render "/shared/errors" %>
  </div>

  <div class="new-answer-form">
    <%= form_for :answer, url: question_answers_path(@question.id), remote: true, authenticity_token: true, method: :create do |f| %>

      <p>
        <%= f.text_area :content %>
      </p>

      <p>
        <%= f.submit "Submit Your Answer" %>
      </p>
    <% end %>
  </div>
</div>

app/views/answers/_show.html.erb
<div class="answer-container">
  <h3>Answer</h3>
<div class="vote-container">
  <%= button_to '+', question_answer_votes_path(@question.id, @old_answer.id), params: {vote_value: 1}, remote: true, authenticity_token: true  %>
  <span id='vote-counter'><%= @old_answer.vote_count %><br></span>
  <%= button_to '-', question_answer_votes_path(@question.id, @old_answer.id), params: {vote_value: -1}, remote: true, authenticity_token: true  %>
</div>
<div class="old-answer-container">
  <%= @old_answer.content %><br>
</div>
</div>

app/views/answers/index.html.erb
<!-- Answers should return a partial to the over arching question page.  -->